name: Deploy DJR Ferro Aço

on:
  push:
    branches:
      - main
    paths:
      - 'djr-ferro-aco/**' # Monitora apenas esta pasta

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Project
        working-directory: ./djr-ferro-aco
        run: |
          npm install
          npm run build

      - name: Deploy via FTP to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Envia apenas o conteúdo da pasta dist (build final)
          local-dir: ./djr-ferro-aco/dist/ 
          # Pasta de destino no seu FTP da Hostinger
          server-dir: /domains/brunorosa.tech/public_html/djr-ferro-aco/dist/